version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name xam-ec2-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  create_infrastructure: 
      docker:
        - image: cimg/aws:2022.11
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file ec2.yml \
                --parameter-overrides file://ec2.json \
                --stack-name xam-ec2-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  smoke_test:
      docker:
        - image: cimg/aws:2022.11
      steps:
        #- run: apk add --update curl
        - run:
            name: smoke test
            command: |
              TEST=XAM
              # Test if website exists
              if [[ $TEST = "YXAR" ]];then
                return 0
              else
                return 1
              fi
        - destroy_environment                    

workflows:
  create-ec2-smoke-test:
    jobs:
      - create_infrastructure
      - smoke_test:
          requires:
            - create_infrastructure

# VS Code Extension Version: 1.4.0